### ISSUE TITLE
challenge_achievement member_id 컬럼 삭제

### ISSUE THREAD

**Issue by hee9841** [dnd-side-project/dnd-11th-2-backend#100]
## 📌 작업 요구 사항 요약

- challenge_achievement member_id 컬럼을 삭제 합니다.

## 📋 상세 요구 사항

- X

## 🤔 예상 구현 방법

- X

**Comment by Jaewon-pro** [comment]
`challenge_achievement` 테이블에 `has_percentage`, `percentage` 필드는 없어도 될 것 같은데 어떻게 생각하시나요?

`achievementValue`, `startValue`, `endValue` 3개 모두 저장해서 percentage를 계산할 수 있어요.

그래서 `percentage `컬럼을 없애서 `challenge_achievement` 테이블 컬럼을 단순하게 하고 싶어서요

**Comment by hee9841** [comment]
`challenge_achievement`테이블에서  `achievement_value`, `startValue`, `endValue` 값은 선택한 `challenge` 테이블의 목표 타입이 PACE가 하나라도 들어가면 없는 값이라서 null로 들어가는 문제가 있어서 이 부분에 대해 저도 고민을 했는데요.

혹시 `challenge_achievement` 테이블에서 `has_percentage`, `percentage`, `achievement_value`, `startValue`, `endValue` 컬럼을 없애고
새로 challenge_achievement_percentage 테이블을 만드는건 어떻게 생각하시나요?
percentage는 타입이 시간이나 거리이나 다르게 계산이 되는데 select할때만다 나눠서 리턴하는 것 보다
저장할 때만 계산해서 넣는게 더 좋을 것 같아요.
|컬럼|내용|
|------|---|
|id||
|challenge_achievement_id|챌린지 성취 테이블 id(fk)|
|achievement_value|달성 값|
|startValue|퍼센테이지 시작 값|
|endValue|퍼센테이지 끝 값|
|percentage|퍼센테이지 값|

**Comment by Jaewon-pro** [comment]
타입이 PACE인 경우, `challenge_achievement` 테이블에 NULL 필드가 생긴다는 점이 고민되네요

말씀하신 것처럼 percentage 부분이 현제 mvp에서는 필요 없으니,
`challenge_achievement_percentage`라는 테이블로 분리하는 게 적절하다고 생각해요 😄

- challenge 타입의 경우
```sql
select *
from running_record
join challenge_achievement on ~
-- left join challenge_achievement_percentage on ~ 테이블로만 분리하고 추후 추가
```

- goal 타입의 경우
```sql
select *
from running_record
join goal_achievement on ~
```

---
percentage는 타입이 시간이나 거리에 상관없이 달성 값, 시작, 끝 3개만 있으면 퍼센트 계산이 가능해요

int 타입으로 저장하고 있는데, 나중에 소수점까지 반환하는 경우에 대처하지 못하게 돼요

퍼센트 계산은 DB가 아닌 was에서 처리하거나 client 단에서 처리할수 있어서,
percentage 컬럼이 없는게 저는 좋은 것 같아요
