### ISSUE TITLE
challenge, challenge_achievement 테이블 구조 변경

### ISSUE THREAD

**Issue by hee9841** [dnd-side-project/dnd-11th-2-backend#102]
## 📌 작업 요구 사항 요약

- enum으로 되어있었던 challengeData를 테이블로 변경합니다.
- challenge_achievement테이블의 구조를 변경합니다.

## 📋 상세 요구 사항

- enum으로 되어있었던 challengeData를 `challenge` 테이블과 `challenge_goal_condition` 테이블로 변경합니다.

`challenge` 테이블
|컬럼|내용|
|------|---|
|id||
|name|챌린지 이름|
|expected_time|예상 소요 시간|
|challenge_type|챌린지 타입(어제의 기록, 오늘의, ..등)|
|imge_url|챌린지 이미지 url|

`challenge_goal_condition` 테이블(챌린지의 목표에 관한 조건을 저장하는 테이블)
|컬럼|내용|
|------|---|
|id||
|challenge_id|챌린지 id(fk)|
|goal_value|목표 값(시간:초, 거리:미터, 페이스:초 단위)|
|goal_type|목표 타입(거리, 시간, 페이스 등)|
|comparison_type|비교 타입(같음, 더 큼, 저 적음 등)|

- `challenge_achievement` 테이블을 다음과 같이 구조를 변경합니다.
   -  `has_percentage`, `percentage`, `achievement_value`, `start_value`, `end_value` 컬럼을 삭제합니다.
   - `challenge_achievement_percentage` 테이블을 아래와 같이 새로 구성합니다.

`challenge_achievement_percentage` 테이블
|컬럼|내용|
|------|---|
|id||
|challenge_achievement_id|챌린지 성취 테이블 id(fk)|
|achievement_value|달성 값|
|start_value|퍼센테이지 시작 값|
|end_value|퍼센테이지 끝 값|

## 🤔 예상 구현 방법

- 변경된 테이블에 따라 dto등을 수정합니다.
- 챌린지 성취 관련 저장 로직을 수정합니다.
- 챌린지 성취 관련 조회는 러닝 기록을 조회할 때 조인해서 가져올 수 있게 합니다.

**Comment by hee9841** [comment]
@Jaewon-pro 리뷰 부탁드립니다 😄

**Comment by Jaewon-pro** [comment]
challenge 테이블의 `expected_time`은 `ChallengeData`처럼 varchar인가요?
다른 테이블과 유사하게 `expected_time`은 초단위 정수로 저장하는 건 어떻게 생각하시나요?

페이스의 경우, `0분`으로 표현하는데, 컬럼을 NULL을 허용하고 NULL로 저장하면 어떨까요?

**Comment by hee9841** [comment]
`expected_time`은 초 단위로 저장하게 되면 초 단위 값을 "MM분" 형식으로 포멧팅하는 과정이 더 들어가기도 하고, 해당 값은 따로 계산을 하는데 사용되지 않고 단순히 사용자한테 보여지는 값이라서 굳이 초 단위 정수로 저장할 필요가 없다고 생각합니다.

제 생각에는  varchar로 저장하는게 더 괜찮다고 생각하는데 어떻게 생각하시나요?

**Comment by Jaewon-pro** [comment]
다국어 지원시, 포멧팅하는 과정은 client 단에서 처리해야 할 것 같아요.

그런데 저희 서비스는 다국어 지원을 할 예정이 없으므로 varchar로 하면 될 것 같아요

**Comment by hee9841** [comment]
그럼 이대로 진행하겠습니다!
