### ISSUE TITLE
`scale` 테이블에 순서 정보 저장 필요

### ISSUE THREAD

**Issue by Jaewon-pro** [dnd-side-project/dnd-11th-2-backend#127]
## 📌 작업 요구 사항 요약

- `scale` 테이블에 순서 정보를 저장해야 합니다.

## 🤔 예상 구현 방법

- `scale` 테이블에 `index`라는 컬럼을 새로 추가합니다.
- `Scale` 도메인 클래스가 없는데, 추가하도록 합니다.
- `start`(출발지), `end`(목적지) 정보를 담기 위한 컬럼을 2개 추가합니다.

**Comment by hee9841** [comment]
저희 도착지, 목적지 컬럼도 필요할 것 같아요!

**Comment by Jaewon-pro** [comment]
> 저희 도착지, 목적지 컬럼도 필요할 것 같아요!

출발지, 목적지는 VARCHAR로 하면 될까요?

- 출발지(서울), 목적지(인천)
