### ISSUE TITLE
혼자 뛰기 기능

### ISSUE THREAD

**Issue by Jaewon-pro** [dnd-side-project/dnd-11th-2-backend#30]
## 📌 작업 요구 사항 요약

- 혼자 뛰기 완료시, 러닝 기록을 저장해야 합니다.
- 달린 코스, 페이스, 시작 시간, 종료 시간을 저장해야 합니다.

## 📋 상세 요구 사항

- 혼자 뛰기가 끝났을때, 클라이언트에서 서버로 데이터를 한번 전송합니다.
- 혼자 뛰기가 끝났을때, 서버는 클라이언트로 해당 러닝에 대한 정보를 반환해야 합니다.

## 🤔 예상 구현 방법

- 실시간이 아니므로 rest api로 구현합니다.

**Comment by Jaewon-pro** [comment]
페이스를 string으로 받되, 0'00" 포맷을 사용합니다.

**Comment by Jaewon-pro** [comment]
@hee9841 님 저희 러닝 기록 데이터에 z 축( 고도 ) 정보도 같이 저장하면 어떨까요?

현재 기획상에는 고도 정보는 없지만, 추후 추가할 가능성도 있을 것 같아요.

만약 고도 정보를 넣기 위해 2D 데이터가 있는 상태에서 3D로 변환하려면,
바로 변경하지 못하고 2D 데이터를 3D로 복제하고 원래 2D 데이터 컬럼을 삭제해야 해요.

||`LineString`|`LineStringZ`|
|--|--|--|
||2D 선형 지오메트리. 각 포인트는 두 개의 좌표 (x, y)|3D 선형 지오메트리. 각 포인트는 세 개의 좌표 (x, y, z)|
|Byte (한 컬럼 기준)|77|109|

**Comment by hee9841** [comment]
확장 가능성을 위해 z축도 정보도 같이 저장하면 좋을것 같네요👍

**Comment by Jaewon-pro** [comment]
z축 정보도 같이 저장하도록 하는 타입(LineStringZ)으로의 변경 PR은 따로 분리해서 올리도록 할께요!
