### ISSUE TITLE
오늘의 챌린지 기능 구현

### ISSUE THREAD

**Issue by Jaewon-pro** [dnd-side-project/dnd-11th-2-backend#39]
## 📌 작업 요구 사항 요약

- 오늘의 챌린지 조회 API가 필요합니다.
- ~오늘의 챌린지는 사용자의 이전 러닝 기록을 기준으로 합니다.~
- 오늘의 챌린지는 날짜에 따라 랜덤하게 조회 합니다.

## 📋 상세 요구 사항

- 챌린지의 타입은 다음과 같습니다.
   - 챌린지 타입은 enum으로 관리합니다.
   - 이전 기록을 사용하는 타입은 앞에 이전 기록을 사용한다는 접두사를 붙여 사용합니다.
- 사용자가 이전 기록이 없으면 이전 기록을 이용해서 사용하는 챌린지는 가져오지 않습니다.
- 각 종류에 따라 랜덤(날짜 기준으로)하게 챌린지를 가져옵니다.
  - 각 종류의 비율은 현재 정해진 챌린지 기준으로 같은 비율로 가져옵니다.
  - 만약 추후 챌린지의 종류가 늘어나면 우선 순위를 정해 랜덤함수를 구성할 예정입니다.

## 🤔 예상 구현 방법

1. erd를 구성후 임시 데이터를 추가합니다.
2. 날짜 기준으로 랜덤 함수를 구성할 방법에 대해 조사 후 설계 및 구현 합니다.

**Comment by Jaewon-pro** [comment]
- 문구는 3가지(목표, 달성, 실패)가 있을 것 같아요
- 실패하더라도 얼마 뛰었는지( 막대바 )에 대한 정보는 필요해요
- 단위는 같이 문구에 포함하고, 변동되는 수치는 `%s`나 `{}`를 문구 문자열에 같이 두면 좋을 것 같아요
  - `어제보다 {0}m 더 달렸어요!`
  - `오늘은 %s분이나 달렸어요`
  - {0}과 같은 place holder 방식은 [`MessageFormat`](https://docs.oracle.com/javase/7/docs/api/java/text/MessageFormat.html)을 사용
  - `%s`는 [`String.format`](https://docs.oracle.com/javase/6/docs/api/java/lang/String.html#format%28java.lang.String,%20java.lang.Object...%29)을 사용할 수 있지만,
     %d나 %s로 타입을 정해야 하고 여러 %s가 있을 때, 단어가 들어갈 순서를 변경하려면 java 코드를 수정해야 해요

---
### 어제와 비교 목표
- 어제보다 000m 더 달리기
  - 목표 문구: 어제보다 000m 더 달리기
  - 달성시 문구: 어제보다 000m 더 달렸어요
  - 실패시 문구: 어제보다 000m 더 달렸지만 다 채우지 못했어요! 다음에는 ~와 같은 격려 문구

### 한번 러닝에 얼마 목표
- 오늘 000m 뛰기
  - 목표 문구: 000m 달리기
  - 달성시 문구: 000m 달렸어요
  - 실패시 문구: 000m 달렸지만 다 채우지 못했어요 등의 격려 문구

**Comment by hee9841** [comment]
## 문구 관련 변경 사항
- 달성 시, 실패 시 문구 관련해서 변경사항
   - 이전 형식 : `어제보다 000m 더 달렸어요` 등
   - 바뀐 형식
     - 성공, 실패 시 문구 동일 : 정말 대단해요!!....~~, 아쉬워요.....
## 변경 사항
- challenge 테이블에 목표 내용(`오늘 30분 동안 뛰기` 등)을 저장하는 방식으로 변경
- 러닝 결과의 성공,실패 멘트는 enum으로 관리해서 사용자가 챌린지 성공이면 성공멘트, 실패면 격려멘트를 가져오게 구성

**Comment by Jaewon-pro** [comment]
스크럼 정리

- 랜덤 기능 삭제 결정하기
- 타입의 종류 2가지
  - 날짜 ( 어제와 비교, 오늘 신규 )
  - 목표 ( 시간, 거리, 정해진 목표보다 빠르게 )
- 챌린지는 table 대신 enum으로 저장
- 추후 변동이 없어지거나 새로운 챌린지 종류를 추가해야 할 때,
   적절한 table로 구성하고 enum에서 이전하기

**Comment by hee9841** [comment]
## 챌린지 완료 유무에 대한 고민
몇km 몇분안에 완주 관련 챌린지
1.  페이스 + 거리로 체크
      - 1km 6분안에 완주하기 -> 평균 페이스 600 이하, 1km이상 완주 시 성공
      - 5km 30분안에 완주 -> 평균 페이스 600이하, 5km이상 완주 시 성공
2. 0~해당 km까지 드는 시간으로 체크
    - 1km 6분안에 완주 -> 사용자가 1km에서의 시각-러닝 시작 시각 == 6분이면 성공
 
2번의 경우 러닝 기록 좌표에 시간 데이터도 필요할 것 같아요.

**Comment by Jaewon-pro** [comment]
시간 데이터가 없으니 1번으로 해주시면 될 것 같아요 👍

좌표에 시간 데이터도 포함한다면, 2번은 시간을 기준으로 찾을 수도 있을 것 같아요.
- 달린지 6분일때 위치한 좌표를 찾아서(이분 탐색), 시작점부터 6분일때의 좌표간 이동 거리가 6km인지 확인
