### ISSUE TITLE
목표 성취 erd 구성

### ISSUE THREAD

**Issue by hee9841** [dnd-side-project/dnd-11th-2-backend#92]
## 📌 작업 요구 사항 요약

- 목표 성취 관련 테이블 erd를 구성합니다.

## 📋 상세 요구 사항

- 목표 성취 관련 테이블 erd를 구성합니다.

## 🤔 예상 구현 방법

-

**Comment by hee9841** [comment]
## 리뷰 요청 사항
b1a065d07d7ea0c242f44b91cd77bd60e847b259

- 기존 챌린지 성취 기록이 챌린지 도메인에 들어가 있는데,
목표 성취와 챌린지 성취 기록을 같은 도메인으로 묶으면 괜찮을 것 같은데 혹시 어떻게 생각하시나요?
챌린지 성취 기록이 챌린지하고 관련이 많아서 챌린지 도메인에 두는 것도 맞는 것 같은데 고민이네요.
만약 목표 성취와 챌린지 성취를 같은 도메인에 둔다면 네이밍도 고민입니다.

- goalType은 기존 ChallengeGoalType의 네이밍만 바꿔서 같이 사용하면 좋을 것 같은데 이 것도 어떻게 생각하는지 궁금합니다.

**Comment by hee9841** [comment]
그리고 sql 버전 이름은 #91 다음 버전으로 수정해서 올릴게요!

**Comment by Jaewon-pro** [comment]
table 컬럼명 이름만 의견 남겼어요! 그대로 진행하시면 될 것 같아용
