### ISSUE TITLE
2024-08-21

### ISSUE THREAD

**Issue by hee9841** [dnd-side-project/dnd-11th-2-backend#94]

**Comment by hee9841** [comment]
## 진행 사항 공유

## 공유할 이슈
- @seungyooooong 와 협의 후 로그인, 회원가입 api 분리

**Comment by Jaewon-pro** [comment]
## 진행 사항 공유

- 백엔드 발표 자료 준비
- 목표 성취 저장 이후 혼자뛰기 러닝 기록 조회에 챌린지, 목표 조회 부분 수정 예정

## 공유할 이슈
